<a href="https://colab.research.google.com/github/rushikeshlokhande1/Data-Analysis_Pratice/blob/main/Automation_Data_Clening_Scripitpynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [136]:
import pandas as pd
from google.colab import files

In [137]:
file=files.upload()

Saving sales_data_sample.csv to sales_data_sample (1).csv

In [138]:
df = pd.read_csv(next(iter(file)), encoding='latin1')

In [139]:
df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [140]:
df.shape

(2823, 25)

In [141]:
df.columns

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID',
       'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
       'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE',
       'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME',
       'DEALSIZE'],
      dtype='object')

In [142]:
df.columns=df.columns.str.capitalize()

In [143]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Ordernumber       2823 non-null   int64
 1   Quantityordered   2823 non-null   int64
 2   Priceeach         2823 non-null   float64
 3   Orderlinenumber   2823 non-null   int64
 4   Sales             2823 non-null   float64
 5   Orderdate         2823 non-null   object
 6   Status            2823 non-null   object
 7   Qtr_id            2823 non-null   int64
 8   Month_id          2823 non-null   int64
 9   Year_id           2823 non-null   int64
 10  Productline       2823 non-null   object
 11  Msrp              2823 non-null   int64
 12  Productcode       2823 non-null   object
 13  Customername      2823 non-null   object
 14  Phone             2823 non-null   object
 15  Addressline1      2823 non-null   object
 16  Addressline2      302 non-null    object
 17  City              2823 non-null   object
 18  State             1337 non-null   object
 19  Postalcode        2747 non-null   object
 20  Country           2823 non-null   object
 21  Territory         1749 non-null   object
 22  Contactlastname   2823 non-null   object
 23  Contactfirstname  2823 non-null   object
 24  Dealsize          2823 non-null   object
dtypes: float64(2), int64(7), object(16)
memory usage: 551.5+ KB

In [144]:
df

,Ordernumber,Quantityordered,Priceeach,Orderlinenumber,Sales,Orderdate,Status,Qtr_id,Month_id,Year_id,...,Addressline1,Addressline2,City,State,Postalcode,Country,Territory,Contactlastname,Contactfirstname,Dealsize
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [145]:
df.describe()

,Ordernumber,Quantityordered,Priceeach,Orderlinenumber,Sales,Qtr_id,Month_id,Year_id,Msrp
count,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.00000,2823.000000
mean,10258.725115,35.092809,83.658544,6.466171,3553.889072,2.717676,7.092455,2003.81509,100.715551
std,92.085478,9.741443,20.174277,4.225841,1841.865106,1.203878,3.656633,0.69967,40.187912
min,10100.000000,6.000000,26.880000,1.000000,482.130000,1.000000,1.000000,2003.00000,33.000000
25%,10180.000000,27.000000,68.860000,3.000000,2203.430000,2.000000,4.000000,2003.00000,68.000000
50%,10262.000000,35.000000,95.700000,6.000000,3184.800000,3.000000,8.000000,2004.00000,99.000000
75%,10333.500000,43.000000,100.000000,9.000000,4508.000000,4.000000,11.000000,2004.00000,124.000000
max,10425.000000,97.000000,100.000000,18.000000,14082.800000,4.000000,12.000000,2005.00000,214.000000

In [146]:
df.isnull().sum()

Ordernumber            0
Quantityordered        0
Priceeach              0
Orderlinenumber        0
Sales                  0
Orderdate              0
Status                 0
Qtr_id                 0
Month_id               0
Year_id                0
Productline            0
Msrp                   0
Productcode            0
Customername           0
Phone                  0
Addressline1           0
Addressline2        2521
City                   0
State               1486
Postalcode            76
Country                0
Territory           1074
Contactlastname        0
Contactfirstname       0
Dealsize               0
dtype: int64

In [147]:
for col in list(df.columns):
    null_count = df[col].isnull().sum()
    if null_count > len(df) * 0.5:
        df.drop(columns=col, inplace=True)

In [148]:
df=df.dropna()

In [149]:
df.isnull().sum()

Ordernumber         0
Quantityordered     0
Priceeach           0
Orderlinenumber     0
Sales               0
Orderdate           0
Status              0
Qtr_id              0
Month_id            0
Year_id             0
Productline         0
Msrp                0
Productcode         0
Customername        0
Phone               0
Addressline1        0
City                0
Postalcode          0
Country             0
Territory           0
Contactlastname     0
Contactfirstname    0
Dealsize            0
dtype: int64

In [150]:
df.duplicated().sum()

np.int64(0)

In [151]:
df=df.drop_duplicates()

In [152]:
df = df.convert_dtypes()

In [153]:
for col in df.columns:

    if df[col].dtype in ['object', 'string']:

        if df[col].astype(str).str.contains(r'\$', regex=True, na=False).any():

            print("Currency Column:", col)

            df[col] = (
                df[col]
                .astype(str)
                .str.replace(r'[$,]', '', regex=True)
            )

In [154]:
for col in df.select_dtypes(include=['object','string']).columns:
  df[col]=df[col].str.capitalize()

In [155]:
for col in df.columns:
  if df[col].dtype in ['object','string']:
    temp=pd.to_datetime(df[col],errors='coerce')
    sucess_rate=temp.notna().mean()
    if sucess_rate>0.7:
      df[col]=temp
      print(f"{col} identy as date")
    else:
      print("No Date column")

Orderdate identy as date
No Date column
No Date column
No Date column
No Date column
No Date column
No Date column
No Date column
No Date column
No Date column
No Date column
No Date column
No Date column
No Date column

/tmp/ipykernel_1483/1037226953.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp=pd.to_datetime(df[col],errors='coerce')
/tmp/ipykernel_1483/1037226953.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp=pd.to_datetime(df[col],errors='coerce')
/tmp/ipykernel_1483/1037226953.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp=pd.to_datetime(df[col],errors='coerce')
/tmp/ipykernel_1483/1037226953.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp=pd.to_datetime(df[col],errors='coerce')
/tmp/ipykernel_1483/1037226953.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp=pd.to_datetime(df[col],errors='coerce')
/tmp/ipykernel_1483/1037226953.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp=pd.to_datetime(df[col],errors='coerce')
/tmp/ipykernel_1483/1037226953.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp=pd.to_datetime(df[col],errors='coerce')
/tmp/ipykernel_1483/1037226953.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp=pd.to_datetime(df[col],errors='coerce')
/tmp/ipykernel_1483/1037226953.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp=pd.to_datetime(df[col],errors='coerce')
/tmp/ipykernel_1483/1037226953.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp=pd.to_datetime(df[col],errors='coerce')
/tmp/ipykernel_1483/1037226953.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp=pd.to_datetime(df[col],errors='coerce')
/tmp/ipykernel_1483/1037226953.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp=pd.to_datetime(df[col],errors='coerce')
/tmp/ipykernel_1483/1037226953.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp=pd.to_datetime(df[col],errors='coerce')

In [156]:
report = {
    "Rows": df.shape[0],
    "Columns": df.shape[1],
    "Missing Values": df.isnull().sum().sum(),
    "Duplicate Rows": df.duplicated().sum()
}

report

{'Rows': 1749,
 'Columns': 23,
 'Missing Values': np.int64(0),
 'Duplicate Rows': np.int64(0)}

In [157]:
df.head(10)

,Ordernumber,Quantityordered,Priceeach,Orderlinenumber,Sales,Orderdate,Status,Qtr_id,Month_id,Year_id,...,Customername,Phone,Addressline1,City,Postalcode,Country,Territory,Contactlastname,Contactfirstname,Dealsize
1,10121,34,81.35,5,2765.9,2003-05-07,Shipped,2,5,2003,...,Reims collectables,26.47.1555,59 rue de l'abbaye,Reims,51100,France,Emea,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,2003-07-01,Shipped,3,7,2003,...,Lyon souveniers,+33 1 46 62 7555,27 rue du colonel pierre avia,Paris,75508,France,Emea,Da cunha,Daniel,Medium
6,10180,29,86.13,9,2497.77,2003-11-11,Shipped,4,11,2003,...,Daedalus designs imports,20.16.1555,"184, chausse de tournai",Lille,59000,France,Emea,Rance,Martine,Small
7,10188,48,100.0,1,5512.32,2003-11-18,Shipped,4,11,2003,...,Herkku gifts,+47 2267 3215,"Drammen 121, pr 744 sentrum",Bergen,N 5804,Norway,Emea,Oeztan,Veysel,Medium
9,10211,41,100.0,14,4708.44,2004-01-15,Shipped,1,1,2004,...,Auto canal petit,(1) 47.55.6555,"25, rue lauriston",Paris,75016,France,Emea,Perrier,Dominique,Medium
10,10223,37,100.0,1,3965.66,2004-02-20,Shipped,1,2,2004,...,"Australian collectors, co.",03 9520 4555,636 st kilda road,Melbourne,3004,Australia,Apac,Ferguson,Peter,Medium
14,10275,45,92.83,1,4177.35,2004-07-23,Shipped,3,7,2004,...,La rochelle gifts,40.67.8555,"67, rue des cinquante otages",Nantes,44000,France,Emea,Labrune,Janine,Medium
16,10299,23,100.0,9,2597.39,2004-09-30,Shipped,3,9,2004,...,"Toys of finland, co.",90-224 8555,Keskuskatu 45,Helsinki,21240,Finland,Emea,Karttunen,Matti,Small
17,10309,41,100.0,5,4394.38,2004-10-15,Shipped,4,10,2004,...,Baane mini imports,07-98 9555,Erling skakkes gate 78,Stavern,4110,Norway,Emea,Bergulfsen,Jonas,Medium
20,10341,41,100.0,9,7737.93,2004-11-24,Shipped,4,11,2004,...,Salzburg collectables,6562-9555,Geislweg 14,Salzburg,5020,Austria,Emea,Pipps,Georg,Large